<HTML>
<BODY>
<PRE>
<?php
require_once 'phpunit-0.5/phpunit.php';
require_once 'phpunit-0.5/phpunit/gui/setupdecorator.php';
require_once 'phpunit-0.5/phpunit/gui/html.php';



$gui = new PHPUnit_GUI_SetupDecorator(new PHPUnit_GUI_HTML());
$gui->getSuitesFromDir("/usr2/home/nsavard/proj/php-4.3.2RC1/ext/ogr/".
                       "phpunit_tests/", 'php_ogr_testcase', 
                       $exclude = array("php_ogr_testcase18"));

printf("dumping testsuites_list\n");
var_dump($testSuites_list);


/***********************************************************************
*       Assigning needed test variables to use in the setUp() method.
*
************************************************************************/
$strPathToOutputData = "/usr2/home/nsavard/proj/php-4.3.2RC1/ext/ogrtests/".
                       "testcase/";
$strTmpDumpFile = "DumpFile.tmp";
/*Following path is for testing purpose.  To Delete.*/
$strPathToOutputData2 = "/usr2/home/nsavard/proj/php-4.3.2RC1/ext/ogrtests/".
                       "testcase2/";




$strPathToData = "/usr2/home/nsavard/proj/php-4.3.2RC1/ext/ogr/phpunit_tests".
                 "/data/mif";
$strBadPathToData = "/usr2/home/nsavard/proj/php-4.3.2RC1/ext/ogr/".
                    "phpunit_tests/dataBad/mif";
$strPathToStandardData = "/usr2/home/nsavard/proj/php-4.3.2RC1/ext/ogr".
                         "/phpunit_tests/data/testcase/";

$strFilename = "road.tab";

$iSpatialFilter[0] = 3350000;  /*xmin*/
$iSpatialFilter[1] = 4210400;  /*ymin*/
$iSpatialFilter[2] = 3580000;  /*xmax*/
$iSpatialFilter[3] = 4280000;  /*ymax*/

$strFormat = "MapInfo File";
$iDriver =5;
$nLayerCount = 10;
$astrOptions[0] = "FORMAT=MIF";



/***********************************************************************
*      Setting variables for used commands.
*                         
************************************************************************/


if (!isset($ogrinfo)){
    $ogrinfo = "/usr1/local/bin/ogrinfo -al ";
}
if (!isset($diff)){
    $diff = "diff --brief --ignore-matching-lines=\"INFO:\" ";
}

/***********************************************************************
*        Executing test cases.                    
*                         
************************************************************************/

$gui->show();

?>
</PRE>
</BODY>
</HTML>
